# SPDX-License-Identifier: GPL-2.0

dtbo-$(CONFIG_ARCH_SUNXI) += \
	bpi-m4berry-i2c4.dtbo \
	bpi-m4berry-nxez-pcm512x-hifi.dtbo \
	bpi-m4berry-waveshare-wm8960-hifi.dtbo

targets += $(dtbo-y) $(scr-y) $(dtbotxt-y)

always		:= $(dtbo-y) $(scr-y) $(dtbotxt-y)
clean-files	:= *.dtbo *.scr
